In [3]:
import pandas as pd
import glob
import os

# print(os.getcwd())

csv_dir = '../raw_csv/'
csv_files = glob.glob(os.path.join(csv_dir, '*.csv'))

print('CSV file found:')
for f in csv_files:
    print(f)

CSV file found:
../raw_csv/microchip_export.csv
../raw_csv/wafer_export.csv
../raw_csv/microelectronic_export.csv
../raw_csv/electronic_packaging_export.csv
../raw_csv/semiconductors_export.csv
../raw_csv/semiconductor_export.csv
../raw_csv/Integrated_Circuit_export.csv
../raw_csv/lithography_export.csv
../raw_csv/silicon_export.csv

In [23]:
for files in csv_files:
    df = pd.read_csv(files)
    count_entries = len(df)
    print(f"{os.path.basename(files)}: {count_entries} entries.")

microchip_export.csv: 2 entries.
wafer_export.csv: 38 entries.
microelectronic_export.csv: 16 entries.
electronic_packaging_export.csv: 5 entries.
semiconductors_export.csv: 197 entries.
semiconductor_export.csv: 197 entries.
Integrated_Circuit_export.csv: 18 entries.
lithography_export.csv: 4 entries.
silicon_export.csv: 115 entries.

In [35]:
for files in csv_files:
    df = pd.read_csv(files)
    print(df.shape)

(2, 24)
(38, 24)
(16, 24)
(5, 24)
(197, 24)
(197, 24)
(18, 24)
(4, 24)
(115, 24)

In [24]:
df = pd.read_csv(csv_files[0])
df.head()

,ID,Sponsor Award Number,Account,Sponsor,sponsorNameNotAsLink(),Prime Sponsor,primeSponsorNotAsLink(),PI Last,PI First,Lead Financial Unit Code,...,Obligated,Anticipated,Award Start Date,Obligated End Date,Award End Date (Anticipated),Teams,Status,Authorized Total,Awarded Total,Proposed Total
0,AWD00015655,83090002,<a href='https://era2.oked.asu.edu/Grants/sd/R...,EPA: Region 9,EPA: Region 9,NaN,NaN,Wang,Joseph,B1314,...,"$285,441","$285,441",11/1/2004,11/30/2007,11/30/2007,NaN,Closed,"$285,441","$285,441","$285,441"
1,AWD00034925,21P622-02,<a href='https://era2.oked.asu.edu/Grants/sd/R...,Texas Tech University (TTU),Texas Tech University (TTU),National Science Foundation (NSF),National Science Foundation (NSF),Jiao,Yang,B1343004,...,"$50,000","$50,000",2/15/2020,1/31/2023,1/31/2023,Team 2,Expired,"$50,000","$50,000","$50,000"

In [5]:
print(df.columns.to_list())

['ID', 'Sponsor Award Number', 'Account', 'Sponsor', 'sponsorNameNotAsLink()', 'Prime Sponsor', 'primeSponsorNotAsLink()', 'PI Last', 'PI First', 'Lead Financial Unit Code', 'Lead Financial Unit', 'leadFinancialUnitNotAsLink()', 'Short Title', 'AMT GCO', 'Obligated', 'Anticipated', 'Award Start Date', 'Obligated End Date', 'Award End Date (Anticipated)', 'Teams', 'Status', 'Authorized Total', 'Awarded Total', 'Proposed Total']

In [6]:
cols_to_drop = [
    'Account', 'sponsorNameNotAsLink()', 'primeSponsorNotAsLink()', 'leadFinancialUnitNotAsLink()', 'AMT GCO', 'Obligated and Anticipated',
    'Award End Date (anticipated)', 'Teams', 'Status',
    'Authorized total', 'Proposed Total'
]

df_cleaned = df.drop(columns=[col for col in cols_to_drop if col in df.columns])

df_cleaned.head()

,ID,Sponsor Award Number,Sponsor,Prime Sponsor,PI Last,PI First,Lead Financial Unit Code,Lead Financial Unit,Short Title,Obligated,Anticipated,Award Start Date,Obligated End Date,Award End Date (Anticipated),Authorized Total,Awarded Total
0,AWD00015655,83090002,EPA: Region 9,NaN,Wang,Joseph,B1314,Chemical Engineering,Nanomaterial-Based Microchip Assays for Contin...,"$285,441","$285,441",11/1/2004,11/30/2007,11/30/2007,"$285,441","$285,441"
1,AWD00034925,21P622-02,Texas Tech University (TTU),National Science Foundation (NSF),Jiao,Yang,B1343004,IAFSE-SEMTE: Materials Science and Engineering,Isolation and Identification of Heterogeneous ...,"$50,000","$50,000",2/15/2020,1/31/2023,1/31/2023,"$50,000","$50,000"

In [8]:
cleaned_dfs = []

for files in csv_files:
    temp_df = pd.read_csv(files)
    temp_df = temp_df.drop(columns=[cols for cols in cols_to_drop if cols in temp_df.columns])
    cleaned_dfs.append(temp_df)

print(f"Cleaned {len(cleaned_dfs)} files.")

Cleaned 9 files.

In [17]:
combined_df = pd.concat(cleaned_dfs, ignore_index = True)
print(combined_df.shape)
combined_df.head()

(592, 16)

,ID,Sponsor Award Number,Sponsor,Prime Sponsor,PI Last,PI First,Lead Financial Unit Code,Lead Financial Unit,Short Title,Obligated,Anticipated,Award Start Date,Obligated End Date,Award End Date (Anticipated),Authorized Total,Awarded Total
0,AWD00015655,83090002,EPA: Region 9,NaN,Wang,Joseph,B1314,Chemical Engineering,Nanomaterial-Based Microchip Assays for Contin...,"$285,441","$285,441",11/1/2004,11/30/2007,11/30/2007,"$285,441","$285,441"
1,AWD00034925,21P622-02,Texas Tech University (TTU),National Science Foundation (NSF),Jiao,Yang,B1343004,IAFSE-SEMTE: Materials Science and Engineering,Isolation and Identification of Heterogeneous ...,"$50,000","$50,000",2/15/2020,1/31/2023,1/31/2023,"$50,000","$50,000"
2,AWD00002990,DMR8310649-04,National Science Foundation (NSF),NaN,Carpenter,Ray,B1719,KE-CF: Eyring Materials Center; CLAS,ELECTRICALLY ACTIVE DEFECTS IN PROCESSED SILIC...,$0,$0,8/1/1983,5/31/1988,5/31/1988,$0,$0
3,AWD00003465,CK 990303,Shell Oil Company Foundation,NaN,Sirkis,Murray,B1310,IAFSE-ECEE: Electrical Engineering,MICROWAVE HEATING OF LOW-RESISTIVITY SEMICONDU...,"$50,000","$50,000",11/27/1984,12/31/1989,12/31/1989,"$50,000","$50,000"
4,AWD00005455,89SJ173,SRCCO Inc.,NaN,Raupp,Gregory,B1314,Chemical Engineering,PROCESS DEVELOPMENT TOOLS FOR SINGLE WAFER L P...,"$20,500","$20,500",12/1/1989,12/31/1990,12/31/1990,"$20,500","$20,500"

In [19]:
output_path = '../cleaned_csv/combined_cleaned_data.csv'
combined_df.to_csv(output_path, index = False)

print(f"saved cleaned and combined data to {output_path}")

saved cleaned and combined data to ../cleaned_csv/combined_cleaned_data.csv